#!/bin/bash

git clone https://github.com/My-TRAC/data-model.git
cd data-model/Resources/MYSQLInitDataModel/app
mvn assembly::assembly
cp target/MYSQLInitDataModel-1.0-SNAPSHOT-jar-with-dependencies.jar /root/MYSQLInitDataModel-1.0-SNAPSHOT-jar-with-dependencies.jar
cd /root


git clone https://github.com/My-TRAC/ConfigurationScripts.git
chmod +x ./ConfigurationScripts/*.sh

/root/ConfigurationScripts/waitForSchemaRegistry.sh
/root/ConfigurationScripts/waitForKafkaConenct.sh
/root/ConfigurationScripts/waitForMySQL.sh

sleep 60

java -cp /root/MYSQLInitDataModel-1.0-SNAPSHOT-jar-with-dependencies.jar MYSQLInitDataModel --username $MYSQL_USER --password $MYSQL_PASSWORD --database $MYSQL_DATABASE --topic-names activity,mobility_trace,facility,poi,user,user_chooses_route,user_evaluates_activity,user_joins_group,user_uses_app,user_views_activity --schema-registry http://$SCHEMA_REGISTRY_HOST_NAME:8081 --mysql $MYSQL_HOST':'$MYSQL_PORT


sleep 20

# sources 
# OLD WORKS Incr /root/scripts/setJDBCConnectorCompanionIncr.sh cigo-jdbc-source_COMPANION_BACKEND_prova2 "prova2" "id" "SELECT id,updated_at,username FROM users"
### incrementing+timestamp source(con el script no va, deduzco que el + de icrementing+timestamp casca la query por parametro)
#/root/scripts/setJDBCConnectorCompanionIncTim.sh cigo-jdbc-source_COMPANION_BACKEND_activity "activity" "mytrac_id" "mytrac_last_modified" "SELECT mytrac_id,mytrac_last_modified FROM activity_fakes" 
## WORKS curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_mobility_trace","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "mobility_trace","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT CAST(id as UNSIGNED INTEGER) AS id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,latitude AS trace_lat, longitude AS trace_lon, provider AS trace_prov, trace_time, accuracy AS trace_acc, speed AS trace_speed  FROM user_points","transforms": "RenameField", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified"}}'
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_activity","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "activity","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,created_at AS activity_creation_date,IF(deleted_at is null, 1,0) AS mytrac_is_valid,activity_id,name AS activity_name,latitude AS activity_lat,longitude AS activity_lon,type AS activity_type,FROM_UNIXTIME(start) AS activity_start,FROM_UNIXTIME(end) AS activity_end,timezone AS activity_timezone FROM activity_dbs","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_mobility_trace","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "mobility_trace","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT CAST(id as UNSIGNED INTEGER) AS id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,latitude AS trace_lat, longitude AS trace_lon, provider AS trace_prov, trace_time, accuracy AS trace_acc, speed AS trace_speed  FROM user_points","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_facility","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "facility","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,facility_id,name AS facility_name,latitude AS facility_lat,longitude AS facility_lon,case type when \"bicycle_parking\" then 1 when \"bicycle_repair_station\" then 2 when \"bicycle_rental\" then 3 when \"boat_rental\" then 4 when \"boat_sharing\" then 5 when \"buggy_parking\" then 6 when \"bus_station\" then 7 when \"car_rental\" then 8 when \"car_sharing\" then 9 when \"car_wash\" then 10 when \"vehicle_inspection\" then 11 when \"charging_station\" then 12 when \"ferry_terminal\" then 13 when \"fuel\" then 14 when \"grit_bin\" then 15 when \"motorcycle_parking\" then 16 when \"parking\" then 17 when \"parking_entrance\" then 18 when \"parking_space\" then 19 when \"taxi\" then 20 when \"ticket_validator\" then 21 end as facility_type FROM facility_dbs","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_poi","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "poi","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,poi_id,name AS poi_name,latitude AS poi_lat,longitude AS poi_lon,type as poi_type, amenity as poi_amenity FROM poi_dbs","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion,interest_history AS user_interest_history,interest_hobby AS user_interest_hobby,interest_eating AS user_interest_eating,interest_shopping AS user_interest_shopping FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user_chooses_route","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user_chooses_route","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,CAST(group_id as CHAR) AS group_id,from_name,from_address,from_lon,from_lat,to_name,to_lon,to_lat,to_address,time,mode,max_walk_distance,num_itineraries,max_transfers,user_choice,request_reply FROM trips","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user_evaluates_activity","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user_evaluates_activity","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,activity_id,rating,created_at AS time FROM user_evaluates_activities","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user_joins_group","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user_joins_group","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,CAST(group_id as CHAR) AS group_id,created_at AS time FROM group_users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user_uses_app","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user_uses_app","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,updated_at AS time FROM user_logins","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# sleep 5
curl -X POST $KAFKA_CONNECT_HOST:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user_views_activity","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user_views_activity","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(user_id as CHAR) AS user_id,activity_id,updated_at AS time FROM user_views_activities","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'




# debería curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion,interest_history AS user_interest_history,interest_hobby AS user_interest_hobby,interest_eating AS user_interest_eating,interest_shopping AS user_interest_shopping FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# debería curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion,interest_history AS user_interest_history,interest_hobby AS user_interest_hobby FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# debería curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# debería curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# funcion curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# funcion curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# funcion curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# funcion curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion,interest_history AS user_interest_history,interest_hobby AS user_interest_hobby FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
# funcion curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,FROM_UNIXTIME(UNIX_TIMESTAMP(updated_at)) AS updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,FROM_UNIXTIME(UNIX_TIMESTAMP(created_at)) AS user_registration_date,birth_day AS user_birthday,gender AS user_gender,country AS user_country,nationality AS user_nationality,occupation AS user_occupation,tolerance AS user_tolerance,reliability AS user_reliability,imp_arr AS user_imp_arr,tweets AS user_tweets,traveller_type AS user_traveller_type,marital_status AS user_marital_status,income AS user_income,household AS user_household,working_hours AS user_working_hours,own_cars AS user_car_avail,own_bikes AS user_bike_avail,own_motorcycles AS user_moto_avail,interest_work AS user_interest_work,interest_education AS user_interest_education,interest_health AS user_interest_health,interest_service AS user_interest_service,interest_religion AS user_interest_religion,interest_history AS user_interest_history,interest_hobby AS user_interest_hobby,interest_eating AS user_interest_eating,interest_shopping AS user_interest_shopping FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'

#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,created_at AS user_registration_date,birth_day AS user_birthday, gender AS user_gender, country AS user_country, nationality AS user_nationality, occupation AS user_occupation, reliability AS user_reliability, imp_arr AS user_imp_arr, tolerance AS user_tolerance, income AS user_income, marital_status AS user_marital_status, tweets AS user_tweets, traveller_type AS user_traveller_type, working_hours AS user_working_hours, household AS user_household,  IF(own_cars>0, 1, 0) AS user_car_avail, IF(own_bikes>0, 1, 0) AS user_bike_avail, IF(own_motorcycles>0, 1, 0) AS user_moto_avail, interest_work AS user_interest_work, interest_education AS user_interest_education, interest_health AS user_interest_health, interest_service AS user_interest_service, interest_religion AS user_interest_religion, interest_history AS user_interest_history, interest_hobby AS user_interest_hobby, interest_eating AS user_interest_eating,  interest_shopping AS user_interest_shopping FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,CAST(id as CHAR) AS user_id,created_at AS user_registration_date,19850223 AS user_birthday, 1 AS user_gender, \"Spain\" AS user_country, \"catalana\" AS user_nationality, 1 AS user_occupation, 1 AS user_reliability, 1 AS user_imp_arr, 1 AS user_tolerance, 1 AS user_income, 1 AS user_marital_status, 0 AS user_tweets, 1 AS user_traveller_type, 8 AS user_working_hours, 1 AS user_household,  1 AS user_car_avail, 1 AS user_bike_avail, 1 AS user_moto_avail, 0 AS user_interest_work, 0 AS user_interest_education, 0 AS user_interest_health, 0 AS user_interest_service, 0 AS user_interest_religion, 0 AS user_interest_history, 0 AS user_interest_hobby, 0 AS user_interest_eating, 0 AS user_interest_shopping FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_user","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "user","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at FROM users","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'
#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name": "connector_source_activity","config": {"connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector","tasks.max": 1,"connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'","mode": "timestamp+incrementing","incrementing.column.name": "id","timestamp.column.name": "updated_at","topic.prefix": "activity","poll.interval.ms": 1000,"validate.non.null":false,"timestamp.delay.interval.ms":1000,"query":"SELECT id,updated_at,IF(deleted_at is null, 1,0) AS mytrac_is_valid,IFNULL(activity_id, \"10\") AS activity_id,IFNULL(activity_name, \"10\") AS activity_name  FROM activity_dbs","transforms": "RenameField,createKey,extractLong", "transforms.RenameField.type": "org.apache.kafka.connect.transforms.ReplaceField$Value","transforms.RenameField.renames": "id:mytrac_id,updated_at:mytrac_last_modified","transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey","transforms.createKey.fields":"mytrac_id","transforms.extractLong.type":"org.apache.kafka.connect.transforms.ExtractField$Key","transforms.extractLong.field":"mytrac_id"}}'

sleep 20

# sinks
# OLD WORKS Incr /root/scripts/setJDBCSinkConnector.sh "prova2-sink" "prova2"
### incrementing+timestamp sink
/root/scripts/setJDBCSinkConnector.sh "connector_sink_activity" "activity"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_mobility_trace" "mobility_trace"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_facility" "facility"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_poi" "poi"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user" "user"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user_chooses_route" "user_chooses_route"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user_evaluates_activity" "user_evaluates_activity"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user_joins_group" "user_joins_group"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user_uses_app" "user_uses_app"
# sleep 5
/root/scripts/setJDBCSinkConnector.sh "connector_sink_user_views_activity" "user_views_activity"

#echo "Created basics source and sink"

#sleep 60
#/root/scripts/setJDBCSinkConnector.sh "connector_sink_corrector" "user_joins_group"

#echo "Solved sink error connectors"




#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name":"connector_sink_activity","config": {"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector","tasks.max":"1","topics":"activity","connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'", "key.converter":"io.confluent.connect.avro.AvroConverter","key.converter.schema.registry.url":"http://schema-registry:8081","value.converter":"io.confluent.connect.avro.AvroConverter","value.converter.schema.registry.url":"http://schema-registry:8081","insert.mode":"upsert","batch.size":"0","auto.create":"false","pk.mode":"record_value","pk.fields":"mytrac_id"}}'
#curl -X POST kafka-connect:28083/connectors -H 'Content-Type: application/json' -d '{"name":"connector_sink_mobility_trace","config": {"connector.class":"io.confluent.connect.jdbc.JdbcSinkConnector","tasks.max":"1","topics":"mobility_trace","connection.url": "jdbc:mysql://'$MYSQL_HOST':'$MYSQL_PORT'/'$MYSQL_DATABASE'?user='$MYSQL_USER'&password='$MYSQL_PASSWORD'", "key.converter":"io.confluent.connect.avro.AvroConverter","key.converter.schema.registry.url":"http://schema-registry:8081","value.converter":"io.confluent.connect.avro.AvroConverter","value.converter.schema.registry.url":"http://schema-registry:8081","insert.mode":"upsert","batch.size":"0","auto.create":"false","pk.mode":"record_value","pk.fields":"mytrac_id"}}'


/root/scripts/infinite.sh




    

